{% set python_min = "3.10" %}
{% set name = "txl-kernel" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_kernel-{{ version }}.tar.gz
  sha256: eef9ea5569cd28a476410cd7783a513c8a05a705829e4da7c906ae97e4d288ac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - python-dateutil >=2.8.2
    - pycrdt >=0.10.9,<0.13.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_kernel

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/kernel
  summary: TXL plugin for a kernel driver
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/kernel
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
